### ISSUE TITLE
Better typing for SyncClient.workerProxy

### ISSUE THREAD

**Issue by winniederidder** [alexmojaki/comsync#1]
I believe the correct typing for this value is `Remote<T>` (with Remote being a type exported from Comlink) instead of any. This would allow for proper TypeScript support when calling methods on the workerProxy directly if they are not syncExposed.

**Comment by alexmojaki** [comment]
That sounds right

**Comment by winniederidder** [comment]
Will you open a PR for this, should I fork and add it or will I become a collaborator and add it?
