### ISSUE TITLE
Write before read

### ISSUE THREAD

**Issue by winniederidder** [alexmojaki/comsync#3]
When using pure sync-message, I believe it was possible to have writes occur before reads and still being able to pass these messages correctly. When using SyncClient, an error is thrown if the client is not yet waiting. My use case is the following:
I have batch input that users can fill up, which is then used at runtime. If a request for input occurrs, a race condition manifests between the main thread that already has input and the worker thread that will request input shortly. If the main thread posts the message too soon, then the error "Not waiting for input" is thrown. Adding a small delay using setTimeout before writing is my temporary patch, but ideally the previous functionality is reinstated.

In the past, this was done by generating the uuid for the message at the receiving end and passing it along in the input callback, so that both ends knew which message it was and it could be handled correctly. This does require exposing the messageId again. 
@alexmojaki Do you think this is useful enough to bring back, and in what way?

**Comment by alexmojaki** [comment]
I don't understand how this used to work. Why was the main thread sending input before being told it was needed? How did it know what messageId to send if the worker was generating it?

**Comment by winniederidder** [comment]
There is a short timeframe between the input callback being called and the message being read. You can generate the uuid before calling the input callback to send it along (by calling onEvent). There are two calls here: one to inform Papyros that an input event occurred. The other calls read on the syncExtras object. In the time between these calls, Papyros can already answer the input call as due to batch input, we already know what to send.
![calls](https://user-images.githubusercontent.com/53743234/163560566-ede624ad-ab86-4d2e-8a82-68e2df9baa24.PNG)

**Comment by alexmojaki** [comment]
OK, I understand the problem now.

I think we can solve this nicely without exposing messageIds. SyncExtras can have an internal messageId 'base' (a UUID) and the actual messageId would be `base + i` where `i` starts at 0 and is incremented with each message. So the messageIds are predictable and the main thread can know what messageId to use without having to wait for the worker to send it.

**Comment by winniederidder** [comment]
Only SyncClient would have to know then, as I think we can just use that in writeMessage instead of throwing an error.

**Comment by alexmojaki** [comment]
Yes, both sides would have the base and keep track of `i` in tandem.

**Comment by alexmojaki** [comment]
Can you explain in detail what an API that optionally exposes messageId would look like?

**Comment by winniederidder** [comment]
It would only be useful if the user could have multiple concurrent reads/writes, which doesn't align well with being interruptible. So keeping that as an Error is probably better.
